type User @table {
  displayName: String!
  email: String!
  createdAt: Timestamp!
  shippingAddress: String
  billingAddress: String
  phoneNumber: String
}

type Product @table {
  name: String!
  price: Float!
  description: String!
  createdAt: Timestamp!
  imageUrl: String
  category: String
  stockQuantity: Int
}

type Cart @table {
  user: User!
  createdAt: Timestamp!
}

type CartItem @table(key: ["cart", "product"]) {
  cart: Cart!
  product: Product!
  quantity: Int!
  addedAt: Timestamp!
}

type Order @table {
  user: User!
  orderDate: Timestamp!
  totalAmount: Float!
  status: String!
  shippingAddress: String
  paymentMethod: String
}

type OrderItem @table(key: ["order", "product"]) {
  order: Order!
  product: Product!
  quantity: Int!
  priceAtPurchase: Float!
}