mutation AddProductToCart($cartId: UUID!, $productId: UUID!, $quantity: Int!) @auth(level: USER) {
  cartItem_insert(data: {cartId: $cartId, productId: $productId, quantity: $quantity, addedAt_expr: "request.time"})
}

query GetProductsByCategory($category: String!) @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  products(where: {category: {eq: $category}}) {
    id
    name
    description
    price
    imageUrl
    stockQuantity
  }
}

query GetUserOrders @auth(level: USER) {
  orders(where: {userId: {eq_expr: "auth.uid"}}) {
    id
    orderDate
    paymentMethod
    shippingAddress
    status
    totalAmount
    orderItems_on_order {
      product {
        id
        name
        description
        price
        imageUrl
      }
      quantity
      priceAtPurchase
    }
  }
}

mutation CreateUser($displayName: String!, $email: String!) @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  user_insert(data: {displayName: $displayName, email: $email, createdAt_expr: "request.time", id_expr: "uuidV4()"})
}